sanitize: Fix missing `IORING_OP_PIPE`
Fix build error due to missing `IORING_OP_PIPE`.

```
 sanitize.c:122:17: error: static assertion failed due to requirement \
 'IORING_OP_WRITEV_FIXED + 1 == IORING_OP_LAST': Need an implementation \
 for all IORING_OP_* codes
  122 |         _Static_assert(IORING_OP_WRITEV_FIXED + 1 == IORING_OP_LAST,\
                               "Need an implementation for all IORING_OP_* codes");
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fixes: eca641e0ea37 ("Add support for IORING_OP_PIPE")
Cc: Michael de Lang <michael@volt-software.nl>
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>