src/Makefile: Fix missing bpf_filter.h installation
After a "make install" command, liburing.h fails to compile because
bpf_filter.h is not copied to the destination include directory:

    In file included from .github/workflows/test_build.c:1:
    /usr/include/liburing.h:21:10: fatal error: liburing/io_uring/bpf_filter.h: No such file or directory
    21 | #include "liburing/io_uring/bpf_filter.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.

Add the header to the Makefile's install list to satisfy the dependency.

Fixes: 46b5c4d66232dcadd0f46c875e6fabce3b3dea85 ("src/include/liburing.h: add bpf_filter.h header")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>