Makefile: Fix missing query.h installation
Fix query.h file is not installed when invoking the "make install"
command:

  In file included from a.c:1:
  /usr/include/liburing.h:19:10: fatal error: liburing/io_uring/query.h: No such file or directory
     19 | #include "liburing/io_uring/query.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.

Make sure to install it.

Cc: Pavel Begunkov <asml.silence@gmail.com>
Fixes: 7e565c0116ba ("tests: test the query interface")
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>