test: Remove unused global variables found by clang-23
In preparation for upgrading to Clang 23, fix the following warnings:

  iopoll.c:26:12: error: variable 'no_hybrid' set but not used [-Werror,-Wunused-but-set-global]
  recvmsg-inc-tail.c:66:25: error: variable 'no_recv_mshot' set but not used [-Werror,-Wunused-but-set-global]
  reg-wait.c:26:13: error: variable 'has_kernel_regions' set but not used [-Werror,-Wunused-but-set-global]

`no_hybrid` has been unused since commit c5eead2659ef ("test/iopoll:
fix over-eager no_hybrid check"); `no_recv_mshot` was never used since
it was introduced. `has_kernel_regions` has been unused since commit
30ce99006af9 ("test/reg-wait: basic test + probing of kernel regions").

Fixes: c5eead2659ef ("test/iopoll: fix over-eager no_hybrid check")
Fixes: 3891a21ffec6 ("Add test case for minimum length left for incremental buffers")
Fixes: 30ce99006af9 ("test/reg-wait: basic test + probing of kernel regions")
Cc: Christian Mazakas <christian.mazakas@gmail.com>
Signed-off-by: Ammar Faizi <ammarfaizi2@openresty.com>