tests: Don't use error.h because it's not portable
Sam reports that building liburing tests on Gentoo is broken due to
'#include <error.h>':
```
  x86_64-gentoo-linux-musl-gcc -D_GNU_SOURCE -D__SANE_USERSPACE_TYPES__ \
  -I../src/include/ -include ../config-host.h -pipe -march=native \
  -fno-diagnostics-color -O2 -Wno-unused-parameter -Wno-sign-compare \
  -Wstringop-overflow=0 -Warray-bounds=0 -DLIBURING_BUILD_TEST -o \
  single-issuer.t single-issuer.c helpers.o -Wl,-O1 -Wl,--as-needed \
  -Wl,--defsym=__gentoo_check_ldflags__=0 -L../src/ -luring -lpthread

  single-issuer.c:8:10: fatal error: error.h: No such file or directory
      8 | #include <error.h>
        |          ^~~~~~~~~
```
This header is a GNU extension for glibc. It doesn't exist in musl libc.
Don't use error.h to make it portable.

Bug: https://bugs.gentoo.org/888956
Reported-by: Sam James <sam@gentoo.org>
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>